### ISSUE TITLE
Syntax Error for executing the passhunt.py file

### ISSUE THREAD

**Issue by djtroby** [Viralmaniar/Passhunt#2]
Syntax Error: Non ASCII character '/xe2' in file passhunt.py

**Comment by Viralmaniar** [comment]
@djtroby What version of Python are you using?

**Comment by beamzer** [comment]
@djtroby 
I had the same error, solved it by
editing the file and removed the special characters below the ASCII logo
in lines 22,23 and 24

**Comment by BaderSZ** [comment]
You can also fix it by adding 

`# -*- coding: utf-8 -*-`

after the first line.
