### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by bb78657** [Viralmaniar/Passhunt#8]
Using python 3.5, I got a ssl.SSLErroe CERTIFICATE_VERIFY_FAILED after pressing 2 on command line.

Adding the following to imports fixed this problem:

import os, sys
import urllib.request

import ssl
import io
import bs4 as bs

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context

**Comment by Viralmaniar** [comment]
It's because cirt.net certificate is expired.

Pull the latest from the release section. 

to fix this perform below:

import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context

**Comment by Viralmaniar** [comment]
@bb78657 See above
